### PR TITLE
Fixes for Issues 17 (Blocker) and 15, version bumps

### PR DESCRIPTION
**Pull request by Chuxel**
https://github.com/Microsoft/vsts-cordova-tasks/issues/17
https://github.com/Microsoft/vsts-cordova-tasks/issues/15

### CODE REVIEW

**Comment by lostintangent** [comment]
LGTM! If you want to build the VSIX, I can publish the update in the marketplace.

**Comment by dlevine82** [comment]
LGTMAW

**Comment by Chuxel** [comment]
I'll run a quick double check in mobiledevops and then let's do it!  Will respond when ready.  Also logged a reminder issue to port these fixes to taco-team-build itself since in this case it's in the local copy.  Peter still needs to complete moving this repo to use the npm version.

**Comment by Chuxel** [comment]
+ @BretJohnson

**Pull request merged**
